name: jameya
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.3.0
  go_router: ^17.2.3
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  get_it: ^9.2.1
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  dio: ^5.9.0
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
